services:
  backend:
    build: ./backend
    environment:
      - DEBUG=true
    volumes:
      - ./backend:/app
    # Remove ports - only nginx will expose ports
    networks:
      - app-network

  frontend:
    build: ./frontend
    environment:
      - REACT_APP_API_URL=/api/v1  # Changed to relative URL
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    # Remove ports - only nginx will expose ports
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"  # Single port for everything
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge